env:
  RUBY_VERSION: 3.1.2
  BUNDLER_CACHE_VERSION: 0

name: Linting and tests
on: push
jobs:
  code-linting:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          cache-version: ${{ env.BUNDLER_CACHE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Rubocop linting
        run: bin/bundle exec rubocop
      - name: Yarn install
        run: bin/yarn install
      - name: ESLint
        run: |
            bin/yarn eslint app
            bin/yarn eslint cypress
            bin/yarn eslint config/tailwind.config.js
  tests:
    name: RSpec
    needs: code-linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          cache-version: ${{ env.BUNDLER_CACHE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Precompile assets
        env:
          RAILS_ENV: test
        run: |
          bin/rails assets:precompile
      - name: Run tests
        run: rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
  integration-tests:
    name: Cypress
    needs: code-linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          cache-version: ${{ env.BUNDLER_CACHE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Precompile assets
        env:
          RAILS_ENV: test
        run: |
          bin/rails assets:precompile
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: bundle exec rails s
          wait-on: 'http://localhost:3000'
          browser: chrome
          env: RAILS_ENV=test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
